services:
  schedule:
    build: .
    container_name: tgfp-job-scheduler
    command: "my_scheduler.py"
    environment:
      - DOPPLER_TOKEN=[redacted]
      - DOPPLER_ENV=1
      - TZ=US/Pacific
    restart: unless-stopped
    volumes:
      - ./scripts:/app/scripts
      - ./my_scheduler.py:/app/my_scheduler.py

