# This is an example docker compose file for using the image
services:
  schedule:
    build: .
    container_name: tgfp-job-runner
    command: "my_scheduler.py"
    environment:
      - TZ=US/Pacific
    restart: unless-stopped
    volumes:
      - ./scripts:/app/scripts
      - ./my_scheduler.py:/app/my_scheduler.py
