# This is an example docker compose file for using the image
services:
  schedule:
    build: .
    container_name: tgfp-job-runner
    environment:
      - TZ=US/Pacific
      - SCHEDULE=every 5 seconds
    restart: unless-stopped
    volumes:
      - ./scripts:/app/scripts
