[tool.poetry]
name = "tgfp-job-runner"
version = "4.1.0"
description = "Scripts to help with the running of The Great Football Pool"
authors = ["John Sturgeon <john.sturgeon@me.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10.5,<3.11"
tgfp-lib = "^2.1.1"
tgfp-nfl = "^5.2.0"
hikari = "^2.0.0.dev120"
hikari-lightbulb = "^2.3.3"
arrow = "^1.2.3"
schedule = "^1.2.0"
sentry-sdk = "^1.30.0"
pylint = "^2.17.5"
listmonk-api = "^0.1.2"
apscheduler = "^3.10.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
