[tool.poetry]
name = "tgfp-job-runner"
version = "1.4.0"
description = "Scripts to help with the running of The Great Football Pool"
authors = ["John Sturgeon <john.sturgeon@me.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10.5,<3.11"
doppler-env = "^0.3.1"
tgfp-lib = "^1.16.0"
tgfp-nfl = "^5.2.0"
hikari = "^2.0.0.dev111"
hikari-lightbulb = "^2.2.4"
arrow = "^1.2.3"
schedule = "^1.1.0"
sentry-sdk = "^1.14.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
