[tool.poetry]
name = "tgfp-job-runner"
version = "4.4.0"
description = "Scripts to help with the running of The Great Football Pool"
authors = ["John Sturgeon <john.sturgeon@me.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10.5,<3.11"
tgfp-lib = "^2.1.1"
tgfp-nfl = "^5.2.3"
hikari = "^2.0.0.dev121"
hikari-lightbulb = "^2.3.3"
arrow = "^1.2.3"
sentry-sdk = "^1.31.0"
pylint = "^2.17.5"
paho-mqtt = "^1.6.1"
prefect = "^2.13.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
